### ISSUE TITLE
Hi, where is data/trainSet.data？

### ISSUE THREAD

**Issue by Joanna1212** [acids-ircam/variational-timbre#1]
Hi， I want to run the code, but I cannot find the data~
The error note is : " No such file or directory: 'data/trainSet.data'"

**Comment by esling** [comment]
Hey @Joanna1212 ! Sorry for the delay, we had some trouble with some copyrighted sounds in the dataset, but here is the open-data version finally :)

https://nubo.ircam.fr/index.php/s/SYf9KiYfBtZXFxL
