### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/trainSet.data'

### ISSUE THREAD

**Issue by mgurunathreddy** [acids-ircam/variational-timbre#2]
Hi,

Thank you very much for sharing the code.

Can you please let me know how to create trainSet.data file or where can I get this file.

Thanks,
Gurunath

**Comment by esling** [comment]
Hi @mgurunathreddy , the link to the trainSet.data is written in the README.md, under the first section "Dataset"
https://nubo.ircam.fr/index.php/s/SYf9KiYfBtZXFxL
