### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by Lexvander** [acids-ircam/variational-timbre#3]
python3 dafx2018learn.py --regularization l2 --beta 2 --latent_dims 16 --conditioning pitch --cuda 1 --name var.model --saveroot mod --epochs=10

Traceback (most recent call last):
  File "dafx2018learn.py", line 77, in <module>
    wrong_ids = np.where(audioSet.metadata['octave'] > args.filter)
AttributeError: 'numpy.ndarray' object has no attribute 'metadata'

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux

Ubuntu 18.04 , aarch64, Nvidea Jetson Nano

Anyb idea?

**Comment by jhyrkas** [comment]
I would like to boost this issue as well. It appears that the data used when training for the paper was stored in a different format than the data that is provided in the download link. There is a lot of code for handling the metadata in this code base, but the pickled data from trainSet.data is just a numpy array

**Comment by domkirke** [comment]
Sorry for the abyssal delay, there has been a problem with the dataset pickle. 
Please follow the updated README.md and download the new dataset file, this issue should be fixed!

**Comment by Lexvander** [comment]
> Sorry for the abyssal delay, there has been a problem with the dataset pickle.
> Please follow the updated README.md and download the new dataset file, this issue should be fixed!

That did it, thank you so much for your help :-)
